# Generated by Django 2.1.5 on 2019-01-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='movie',
        ),
        migrations.AddField(
            model_name='tag',
            name='movie',
            field=models.ManyToManyField(to='movies.Movie'),
        ),
    ]
